implemented advanced console report
PragmaticFlow/NBomber pull request #312
Opened 2021-01-29 15:19 UTC by Yaroshvitaliy

improved console report

2021-01-30 08:55 UTC, AntyaDev requested changes

2021-01-30 08:55 UTC, AntyaDev commented on src/NBomber/Contracts.fs
>      Message: string
rename to FullMessage

2021-01-30 08:55 UTC, AntyaDev commented on src/NBomber/DomainServices/Console.fs
> +module internal NBomber.DomainServices.Console
move to Infra
NBomber.Infra.Console

2021-02-05 15:20 UTC, Yaroshvitaliy commented on src/NBomber/Infra/Console.fs
> +let render (renderable: IRenderable) =
try render into text

2021-02-05 15:41 UTC, merged