add StatusCodes hint analyzer
PragmaticFlow/NBomber pull request #404
Opened 2021-06-28 16:27 UTC by yurii-hunter

closes #362 Add hint for HintAnalyzer for the case when statistics has no status code

2021-07-11 05:13 UTC, AntyaDev requested changes

2021-07-11 05:13 UTC, AntyaDev commented on src/NBomber/Domain/HintsAnalyzer.fs
> +    |> Seq.filter(fun step -> Array.isEmpty step.Ok.StatusCodes && Array.isEmpty step.Fail.StatusCodes)
I think that better will be if we check:
if (step.Ok.Request.Count > 0 && Array.isEmpty step.Ok.StatusCodes) || if (step.Fail.Request.Count > 0 && Array.isEmpty step.Fail.StatusCodes)

2021-07-11 05:13 UTC, AntyaDev commented on tests/NBomber.IntegrationTests/HintsAnalyzerTests.fs
> +    test<@ hints.Length>0 @>
add space btw Length > 0
test<@ hints.Length > 0 @>

2021-07-31 13:33 UTC, yurii-hunter commented
@AntyaDev Hi! Sorry, missed that the tests were broken. Fixed now

2021-08-03 12:37 UTC, merged